export const prices = [
  {
    id: 1,
    fiche: '30',
    price: '$5',
    frequency: '/mois',
    name: 'Abonnement mensuel',
    list: [
      "Fiches conforme aux programmes utilisant l'APS/APC",
      "Formation gratuite sur l'APS/APC",
      'Reduction sur la formation en bureautique de base ($10)',
      'Support technique disponible ',
    ],
  },
  {
    id: 2,
    fiche: '30',
    price: '$13.5',
    frequency: '/mois',
    name: 'Abonnement trimestriel',
    list: [
      "Fiches conforme aux programmes utilisant l'APS/APC",
      "Formation gratuite sur l'APS/APC",
      'Formation gratuite en bureautique',
      'Prevision des matieres pour les enseignants',
      'Systeme de suivi des enseignants',
      'Support technique disponible',
    ],
  },
  {
    id: 3,
    fiche: '30',
    price: '$30',
    frequency: '/mois',
    name: 'Abonnement annuel',
    list: [
      "Acces sur DugAssistant pendant toute l'annee scolaire(10 mois)",
      "Fiches conforme aux programmes utilisant l'APS/APC",
      "Formation gratuite sur l'APS/APC",
      'Formation gratuite en bureautique',
      'Prevision des matieres pour les enseignants',
      'Systeme de suivi des enseignants',
      'Support technique disponible',
    ],
  },
];
